package crypto

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"errors"
	"io/fs"
	"os"
	"testing"
)

// These tests are the correctness gate for the v1-sealed encryption
// migration. All fixtures are genuine, server-validated @enbox SDK output
// (generated by scripts/gen-crypto-fixtures); the decrypters must recover the
// SDK plaintext byte-for-byte. Each test skips with a clear message when its
// fixture has not been generated yet, so the package passes standalone.

// readFixture loads a fixture JSON file, skipping the test when absent.
func readFixture(t *testing.T, path string, out any) {
	t.Helper()
	raw, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		t.Skipf("fixture %s not generated yet (run scripts/gen-crypto-fixtures)", path)
	}
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	if err := json.Unmarshal(raw, out); err != nil {
		t.Fatalf("unmarshal fixture %s: %v", path, err)
	}
}

func b64urlBytes(t *testing.T, s string) []byte {
	t.Helper()
	b, err := base64.RawURLEncoding.DecodeString(s)
	if err != nil {
		if b, err = base64.URLEncoding.DecodeString(s); err != nil {
			t.Fatalf("base64url decode %q: %v", s, err)
		}
	}
	return b
}

func b64stdBytes(t *testing.T, s string) []byte {
	t.Helper()
	b, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		t.Fatalf("base64 std decode: %v", err)
	}
	return b
}

// fixtureJWK is an X25519 JWK carried in a fixture.
type fixtureJWK struct {
	KTY string `json:"kty"`
	CRV string `json:"crv"`
	X   string `json:"x"`
	D   string `json:"d"`
}

// fixtureRecord is the subset of a RecordsWrite message the fixture tests
// consume.
type fixtureRecord struct {
	RecordID   string `json:"recordId"`
	ContextID  string `json:"contextId"`
	Descriptor struct {
		Protocol     string            `json:"protocol"`
		ProtocolPath string            `json:"protocolPath"`
		Recipient    string            `json:"recipient"`
		Tags         map[string]string `json:"tags"`
	} `json:"descriptor"`
	Encryption  *Encryption `json:"encryption"`
	EncodedData string      `json:"encodedData"`
}

func TestEncryptionV1ProtocolPathFixture(t *testing.T) {
	var fx struct {
		Protocol               string        `json:"protocol"`
		ProtocolPath           string        `json:"protocolPath"`
		DerivationPath         []string      `json:"derivationPath"`
		ReaderDid              string        `json:"readerDid"`
		ReaderEncPrivateKeyJwk fixtureJWK    `json:"readerEncPrivateKeyJwk"`
		RecordMessage          fixtureRecord `json:"recordMessage"`
		CiphertextB64          string        `json:"ciphertext_b64"`
		ExpectedPlaintextB64   string        `json:"expectedPlaintext_b64"`
	}
	readFixture(t, "testdata/v1/protocolpath.json", &fx)

	if fx.RecordMessage.Encryption == nil {
		t.Fatal("fixture record has no encryption envelope")
	}

	// The fixture's absolute derivation path matches the record coordinates.
	wantPath := BuildProtocolPathDerivation(fx.Protocol, splitProtocolPath(fx.ProtocolPath)...)
	if len(fx.DerivationPath) != len(wantPath) {
		t.Fatalf("derivationPath = %v, want %v", fx.DerivationPath, wantPath)
	}
	for i := range wantPath {
		if fx.DerivationPath[i] != wantPath[i] {
			t.Fatalf("derivationPath = %v, want %v", fx.DerivationPath, wantPath)
		}
	}

	root := b64urlBytes(t, fx.ReaderEncPrivateKeyJwk.D)
	leafPriv, err := DeriveKeyBytes(root, fx.DerivationPath)
	if err != nil {
		t.Fatalf("DeriveKeyBytes: %v", err)
	}

	plaintext, err := DecryptData(
		b64stdBytes(t, fx.CiphertextB64),
		fx.RecordMessage.Encryption,
		leafPriv,
	)
	if err != nil {
		t.Fatalf("DecryptData: %v", err)
	}

	want := b64stdBytes(t, fx.ExpectedPlaintextB64)
	if !bytes.Equal(plaintext, want) {
		t.Fatalf("plaintext mismatch:\n got=%s\nwant=%s", plaintext, want)
	}
}

// sealedRoleAudienceFixture is the sealed role-audience bundle on the real
// wireguard-mesh protocol.
type sealedRoleAudienceFixture struct {
	Description           string     `json:"description"`
	Protocol              string     `json:"protocol"`
	OwnerEncPrivateKeyJwk fixtureJWK `json:"ownerEncPrivateKeyJwk"`
	NetworkRecordID       string     `json:"networkRecordId"`

	AudienceRecords []struct {
		RolePath                 string                  `json:"rolePath"`
		ContextID                string                  `json:"contextId"`
		KeyID                    string                  `json:"keyId"`
		Message                  fixtureRecord           `json:"message"`
		Payload                  AudiencePayload         `json:"payload"`
		AudienceKeyMaterial      RoleAudienceKeyMaterial `json:"audienceKeyMaterial"`
		SealKekInfo              string                  `json:"sealKekInfo"`
		SealingKeyDerivationPath []string                `json:"sealingKeyDerivationPath"`
	} `json:"audienceRecords"`

	SourceRecord struct {
		ProtocolPath   string        `json:"protocolPath"`
		Message        fixtureRecord `json:"message"`
		CiphertextB64u string        `json:"ciphertext_b64u"`
		PlaintextB64u  string        `json:"plaintext_b64u"`
	} `json:"sourceRecord"`

	DeliveryRecord struct {
		Message                        fixtureRecord   `json:"message"`
		ExpectedPayload                DeliveryPayload `json:"expectedPayload"`
		RecipientRolePublicKeyJwk      fixtureJWK      `json:"recipientRolePublicKeyJwk"`
		RecipientRoleKeyDerivationPath []string        `json:"recipientRoleKeyDerivationPath"`
	} `json:"deliveryRecord"`

	RoleHolder struct {
		DID              string     `json:"did"`
		EncPrivateKeyJwk fixtureJWK `json:"encPrivateKeyJwk"`
	} `json:"roleHolder"`
}

// TestEncryptionV1SealedRoleAudienceFixture decrypts the same SDK-encrypted
// source record three ways: (a) with the owner root via the protocolPath
// entry, (b) with each audience key unsealed from its `$encryption/audience`
// record via the owner role-path key, and (c) with the audience key delivered
// to a role holder via the encrypted `$encryption/delivery` record.
func TestEncryptionV1SealedRoleAudienceFixture(t *testing.T) {
	var fx sealedRoleAudienceFixture
	readFixture(t, "testdata/v1/sealed_roleaudience.json", &fx)

	if fx.SourceRecord.Message.Encryption == nil {
		t.Fatal("fixture source record has no encryption envelope")
	}
	want := b64urlBytes(t, fx.SourceRecord.PlaintextB64u)
	sourceCiphertext := b64urlBytes(t, fx.SourceRecord.CiphertextB64u)
	ownerRoot := b64urlBytes(t, fx.OwnerEncPrivateKeyJwk.D)

	// Way (a): owner root → protocolPath leaf key.
	leafPriv, err := DeriveKeyBytes(ownerRoot, BuildProtocolPathDerivation(
		fx.Protocol,
		splitProtocolPath(fx.SourceRecord.ProtocolPath)...,
	))
	if err != nil {
		t.Fatalf("owner leaf derivation: %v", err)
	}
	plaintext, err := DecryptData(sourceCiphertext, fx.SourceRecord.Message.Encryption, leafPriv)
	if err != nil {
		t.Fatalf("owner DecryptData: %v", err)
	}
	if !bytes.Equal(plaintext, want) {
		t.Fatalf("owner plaintext mismatch:\n got=%s\nwant=%s", plaintext, want)
	}

	// Way (b): unseal each audience record with the owner role-path key,
	// then decrypt the source record through its roleAudience entry.
	if len(fx.AudienceRecords) == 0 {
		t.Fatal("fixture has no audience records")
	}
	for _, ar := range fx.AudienceRecords {
		payload := ar.Payload

		// Our seal KEK info string matches the SDK's exactly.
		if got := SealKEKInfo(payload.Protocol, payload.RolePath, payload.ContextID, payload.KeyID); got != ar.SealKekInfo {
			t.Fatalf("SealKEKInfo(%s):\n got=%s\nwant=%s", ar.RolePath, got, ar.SealKekInfo)
		}

		// The payload embedded in the record data matches the parsed one, and
		// the record tags match the tuple. (JSON equality: AudiencePayload
		// holds a pointer field, so struct equality would compare identity.)
		var fromRecord AudiencePayload
		if err := json.Unmarshal(b64urlBytes(t, ar.Message.EncodedData), &fromRecord); err != nil {
			t.Fatalf("parsing audience record encodedData: %v", err)
		}
		fromRecordJSON, _ := json.Marshal(fromRecord)
		payloadJSON, _ := json.Marshal(payload)
		if !bytes.Equal(fromRecordJSON, payloadJSON) {
			t.Fatalf("audience payload mismatch between fixture payload and record data:\n got=%s\nwant=%s", fromRecordJSON, payloadJSON)
		}
		if tags := ar.Message.Descriptor.Tags; tags["protocol"] != payload.Protocol ||
			tags["rolePath"] != payload.RolePath ||
			tags["contextId"] != payload.ContextID ||
			tags["keyId"] != payload.KeyID {
			t.Fatalf("audience tags %v do not match payload %+v", tags, payload)
		}

		// Owner role-path (sealing) key: our helper agrees with the fixture's
		// absolute derivation path.
		sealingPriv, err := DeriveRolePathKey(ownerRoot, payload.Protocol, payload.RolePath)
		if err != nil {
			t.Fatalf("DeriveRolePathKey(owner, %s): %v", ar.RolePath, err)
		}
		fromPath, err := DeriveKeyBytes(ownerRoot, ar.SealingKeyDerivationPath)
		if err != nil {
			t.Fatalf("DeriveKeyBytes(sealingKeyDerivationPath): %v", err)
		}
		if !bytes.Equal(sealingPriv, fromPath) {
			t.Fatalf("DeriveRolePathKey disagrees with fixture sealingKeyDerivationPath %v", ar.SealingKeyDerivationPath)
		}

		audiencePriv, err := UnsealAudienceRecord(&payload, sealingPriv)
		if err != nil {
			t.Fatalf("UnsealAudienceRecord(%s): %v", ar.RolePath, err)
		}
		if base64.RawURLEncoding.EncodeToString(audiencePriv) != ar.AudienceKeyMaterial.PrivateKeyJwk.D {
			t.Fatalf("unsealed audience private key for %s does not match audienceKeyMaterial.privateKeyJwk.d", ar.RolePath)
		}

		dec, err := NewRoleAudienceDecrypter(audiencePriv)
		if err != nil {
			t.Fatalf("NewRoleAudienceDecrypter(%s): %v", ar.RolePath, err)
		}
		if dec.KeyID() != ar.KeyID {
			t.Fatalf("decrypter keyId = %q, fixture keyId = %q", dec.KeyID(), ar.KeyID)
		}
		plaintext, err := dec.Decrypt(sourceCiphertext, fx.SourceRecord.Message.Encryption)
		dec.Close()
		if err != nil {
			t.Fatalf("unsealed audience Decrypt(%s): %v", ar.RolePath, err)
		}
		if !bytes.Equal(plaintext, want) {
			t.Fatalf("unsealed audience plaintext mismatch (%s):\n got=%s\nwant=%s", ar.RolePath, plaintext, want)
		}
	}

	// Way (c): role holder decrypts the delivery record with their own root,
	// then the source record with the delivered audience key.
	if fx.DeliveryRecord.Message.Encryption == nil {
		t.Fatal("fixture delivery record has no encryption envelope")
	}
	expected := fx.DeliveryRecord.ExpectedPayload
	holderRoot := b64urlBytes(t, fx.RoleHolder.EncPrivateKeyJwk.D)

	// The recipient role-path key we derive matches the fixture's derivation
	// path and public key.
	holderRolePriv, err := DeriveRolePathKey(holderRoot, expected.Protocol, expected.RolePath)
	if err != nil {
		t.Fatalf("DeriveRolePathKey(holder): %v", err)
	}
	fromPath, err := DeriveKeyBytes(holderRoot, fx.DeliveryRecord.RecipientRoleKeyDerivationPath)
	if err != nil {
		t.Fatalf("DeriveKeyBytes(recipientRoleKeyDerivationPath): %v", err)
	}
	if !bytes.Equal(holderRolePriv, fromPath) {
		t.Fatal("DeriveRolePathKey disagrees with fixture recipientRoleKeyDerivationPath")
	}
	holderRolePub, err := X25519PublicKey(holderRolePriv)
	if err != nil {
		t.Fatalf("X25519PublicKey: %v", err)
	}
	if base64.RawURLEncoding.EncodeToString(holderRolePub) != fx.DeliveryRecord.RecipientRolePublicKeyJwk.X {
		t.Fatal("derived recipient role public key does not match fixture recipientRolePublicKeyJwk")
	}

	delivery, err := DecryptDeliveryRecord(
		holderRoot,
		expected.Protocol,
		expected.RolePath,
		fx.DeliveryRecord.Message.Encryption,
		b64urlBytes(t, fx.DeliveryRecord.Message.EncodedData),
	)
	if err != nil {
		t.Fatalf("DecryptDeliveryRecord: %v", err)
	}
	if *delivery != expected {
		t.Fatalf("delivery payload mismatch:\n got=%+v\nwant=%+v", delivery, expected)
	}

	deliveredPriv := b64urlBytes(t, delivery.KeyMaterial.PrivateKeyJwk.D)
	deliveredDec, err := NewRoleAudienceDecrypter(deliveredPriv)
	if err != nil {
		t.Fatalf("NewRoleAudienceDecrypter(delivered): %v", err)
	}
	defer deliveredDec.Close()
	plaintext, err = deliveredDec.Decrypt(sourceCiphertext, fx.SourceRecord.Message.Encryption)
	if err != nil {
		t.Fatalf("delivered audience Decrypt: %v", err)
	}
	if !bytes.Equal(plaintext, want) {
		t.Fatalf("delivered audience plaintext mismatch:\n got=%s\nwant=%s", plaintext, want)
	}
}

// wrappedGrantKeyFixture is the pre-supplied-delegate grantKey bundle.
type wrappedGrantKeyFixture struct {
	Description string `json:"description"`
	Protocol    string `json:"protocol"`

	Delegate struct {
		DID                  string     `json:"did"`
		EncPrivateKeyJwk     fixtureJWK `json:"encPrivateKeyJwk"`
		EncRootKeyThumbprint string     `json:"encRootKeyThumbprint"`
	} `json:"delegate"`

	GrantKeyRecord struct {
		Message fixtureRecord     `json:"message"`
		Tags    map[string]string `json:"tags"`
	} `json:"grantKeyRecord"`

	WrappedGrantKeyEnvelope json.RawMessage `json:"wrappedGrantKeyEnvelope"`
	UnwrapKekInfo           string          `json:"unwrapKekInfo"`
	ExpectedGrantKeyPayload GrantKeyPayload `json:"expectedGrantKeyPayload"`

	EncryptedRecord struct {
		ProtocolPath   string        `json:"protocolPath"`
		Message        fixtureRecord `json:"message"`
		CiphertextB64u string        `json:"ciphertext_b64u"`
		PlaintextB64u  string        `json:"plaintext_b64u"`
	} `json:"encryptedRecord"`
}

func TestEncryptionV1WrappedGrantKeyFixture(t *testing.T) {
	var fx wrappedGrantKeyFixture
	readFixture(t, "testdata/v1/wrapped_grantkey.json", &fx)

	delegatePriv := b64urlBytes(t, fx.Delegate.EncPrivateKeyJwk.D)

	// Our computed KEK info matches the SDK's unwrap info exactly.
	if got := protocolPathKEKInfo(fx.Delegate.EncRootKeyThumbprint); got != fx.UnwrapKekInfo {
		t.Fatalf("unwrap KEK info:\n got=%s\nwant=%s", got, fx.UnwrapKekInfo)
	}

	assertPayload := func(what string, payload *GrantKeyPayload) {
		t.Helper()
		wantP := &fx.ExpectedGrantKeyPayload
		if payload.GrantID != wantP.GrantID || payload.Scope != wantP.Scope {
			t.Fatalf("%s: grantId/scope mismatch:\n got=%+v\nwant=%+v", what, payload, wantP)
		}
		if payload.KeyMaterial.KeyID != wantP.KeyMaterial.KeyID ||
			payload.KeyMaterial.PrivateKeyJwk.D != wantP.KeyMaterial.PrivateKeyJwk.D ||
			payload.KeyMaterial.PublicKeyJwk.X != wantP.KeyMaterial.PublicKeyJwk.X {
			t.Fatalf("%s: key material mismatch", what)
		}
		if len(payload.KeyMaterial.DerivationPath) != len(wantP.KeyMaterial.DerivationPath) {
			t.Fatalf("%s: derivationPath mismatch", what)
		}
		for i := range wantP.KeyMaterial.DerivationPath {
			if payload.KeyMaterial.DerivationPath[i] != wantP.KeyMaterial.DerivationPath[i] {
				t.Fatalf("%s: derivationPath mismatch", what)
			}
		}
	}

	// Unwrap from the envelope object.
	fromEnvelope, err := UnwrapGrantKeyEnvelope([]byte(fx.WrappedGrantKeyEnvelope), delegatePriv)
	if err != nil {
		t.Fatalf("UnwrapGrantKeyEnvelope(envelope): %v", err)
	}
	assertPayload("envelope", fromEnvelope)

	// Unwrap from the plaintext grantKey record's data.
	fromRecord, err := UnwrapGrantKeyEnvelope(b64urlBytes(t, fx.GrantKeyRecord.Message.EncodedData), delegatePriv)
	if err != nil {
		t.Fatalf("UnwrapGrantKeyEnvelope(record encodedData): %v", err)
	}
	assertPayload("grantKeyRecord", fromRecord)

	// The record tags reference the delivered key.
	if fx.GrantKeyRecord.Tags["keyId"] != fromRecord.KeyMaterial.KeyID ||
		fx.GrantKeyRecord.Tags["grantId"] != fromRecord.GrantID ||
		fx.GrantKeyRecord.Tags["protocol"] != fromRecord.Scope.Protocol {
		t.Fatalf("grantKey tags %v do not match payload", fx.GrantKeyRecord.Tags)
	}

	// The delivered subtree key decrypts the SDK-encrypted source record.
	if fx.EncryptedRecord.Message.Encryption == nil {
		t.Fatal("fixture encrypted record has no encryption envelope")
	}
	dec, err := NewSubtreeDecrypterFromGrantKey(fromRecord)
	if err != nil {
		t.Fatalf("NewSubtreeDecrypterFromGrantKey: %v", err)
	}
	defer dec.Close()

	plaintext, err := dec.Decrypt(
		b64urlBytes(t, fx.EncryptedRecord.CiphertextB64u),
		fx.EncryptedRecord.Message.Encryption,
		fromRecord.Scope.Protocol,
		fx.EncryptedRecord.ProtocolPath,
	)
	if err != nil {
		t.Fatalf("SubtreeDecrypter.Decrypt: %v", err)
	}
	want := b64urlBytes(t, fx.EncryptedRecord.PlaintextB64u)
	if !bytes.Equal(plaintext, want) {
		t.Fatalf("plaintext mismatch:\n got=%s\nwant=%s", plaintext, want)
	}
}
