package enboxconnect

import (
	"bytes"
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/enboxorg/meshd/pkg/dids/didjwk"
	"github.com/enboxorg/meshd/pkg/jwk"
)

// Fixture tests consume GENUINE @enbox SDK output generated by
// scripts/gen-crypto-fixtures into internal/enboxconnect/testdata/. Byte
// mismatches here indicate real wire bugs in the implementation.

func readFixture(t *testing.T, name string, out any) {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("testdata", name))
	if os.IsNotExist(err) {
		t.Skipf("fixture %s not generated (run scripts/gen-crypto-fixtures)", name)
	}
	if err != nil {
		t.Fatalf("reading fixture %s: %v", name, err)
	}
	if err := json.Unmarshal(data, out); err != nil {
		t.Fatalf("parsing fixture %s: %v", name, err)
	}
}

// x25519PrivFromEdJWK reconstructs the X25519 private key from an Ed25519
// private JWK (d = seed) the way the connect client converts its own key.
func x25519PrivFromEdJWK(t *testing.T, key jwk.JWK) []byte {
	t.Helper()
	if key.CRV != "Ed25519" || key.D == "" {
		t.Fatalf("expected an Ed25519 private JWK, got crv=%q", key.CRV)
	}
	seed, err := base64.RawURLEncoding.DecodeString(key.D)
	if err != nil {
		t.Fatalf("decoding private key d: %v", err)
	}
	if len(seed) != ed25519.SeedSize {
		t.Fatalf("Ed25519 seed length = %d, want %d", len(seed), ed25519.SeedSize)
	}
	identity, err := didjwk.FromPrivateKey(ed25519.NewKeyFromSeed(seed), nil)
	if err != nil {
		t.Fatalf("reconstructing identity: %v", err)
	}
	return identity.X25519PrivateKey
}

// jsonEqual compares two JSON documents structurally.
func jsonEqual(t *testing.T, a, b []byte) bool {
	t.Helper()
	var av, bv any
	if err := json.Unmarshal(a, &av); err != nil {
		t.Fatalf("unmarshaling: %v", err)
	}
	if err := json.Unmarshal(b, &bv); err != nil {
		t.Fatalf("unmarshaling: %v", err)
	}
	return reflect.DeepEqual(av, bv)
}

type requestFixture struct {
	ClientDID              string          `json:"clientDid"`
	ClientKeyID            string          `json:"clientKeyId"`
	ClientEdPrivateKeyJwk  jwk.JWK         `json:"clientEdPrivateKeyJwk"`
	DelegateDID            string          `json:"delegateDid"`
	ConnectServerURL       string          `json:"connectServerUrl"`
	EncryptionKeyB64U      string          `json:"encryptionKey_b64u"`
	ProtectedHeaderJSON    string          `json:"protectedHeaderJson"`
	RequestJWE             string          `json:"requestJwe"`
	ExpectedRequestJWT     string          `json:"expectedRequestJwt"`
	ExpectedRequestPayload json.RawMessage `json:"expectedRequestPayload"`
	WalletURIExample       string          `json:"walletUriExample"`
}

// TestFixtureConnectRequest checks request-JWE interop against genuine SDK
// output: the SDK-produced JWE decrypts with the bundled symmetric key to
// the bundled JWT, the JWT verifies to the bundled payload, our protected
// header matches the SDK's byte-for-byte, and our own construction
// round-trips with the same key.
func TestFixtureConnectRequest(t *testing.T) {
	var fx requestFixture
	readFixture(t, "connect_request.json", &fx)

	key, err := base64.RawURLEncoding.DecodeString(fx.EncryptionKeyB64U)
	if err != nil {
		t.Fatalf("decoding encryption key: %v", err)
	}

	// Our protected-header constant must equal the SDK's byte-for-byte.
	if requestProtectedHeader != fx.ProtectedHeaderJSON {
		t.Errorf("protected header = %s, want %s", requestProtectedHeader, fx.ProtectedHeaderJSON)
	}

	// Decrypt the SDK JWE (walletDecryptRequestJWE also asserts the wire
	// header segment decodes to our exact literal).
	gotJWT := walletDecryptRequestJWE(t, fx.RequestJWE, key)
	if gotJWT != fx.ExpectedRequestJWT {
		t.Errorf("decrypted JWT does not match expectedRequestJwt")
	}

	payload, err := verifyJWT(gotJWT)
	if err != nil {
		t.Fatalf("verifying SDK request JWT: %v", err)
	}
	if !jsonEqual(t, payload, fx.ExpectedRequestPayload) {
		t.Errorf("verified payload differs from expectedRequestPayload:\n got: %s\nwant: %s", payload, fx.ExpectedRequestPayload)
	}

	var request EnboxConnectRequest
	if err := json.Unmarshal(payload, &request); err != nil {
		t.Fatalf("parsing request payload: %v", err)
	}
	if request.ClientDID != fx.ClientDID {
		t.Errorf("clientDid = %q, want %q", request.ClientDID, fx.ClientDID)
	}
	if request.DelegateDID != fx.DelegateDID {
		t.Errorf("delegateDid = %q, want %q", request.DelegateDID, fx.DelegateDID)
	}
	if request.ResponseMode != "direct_post" {
		t.Errorf("responseMode = %q, want direct_post", request.ResponseMode)
	}

	// The JWT kid must be the client DID's verification method id exactly
	// as didjwk resolution yields it — the fixture bundles it.
	headerRaw, err := base64.RawURLEncoding.DecodeString(strings.Split(gotJWT, ".")[0])
	if err != nil {
		t.Fatalf("decoding JWT header: %v", err)
	}
	var header jwtHeader
	if err := json.Unmarshal(headerRaw, &header); err != nil {
		t.Fatalf("parsing JWT header: %v", err)
	}
	if header.KID != fx.ClientKeyID {
		t.Errorf("JWT kid = %q, want %q", header.KID, fx.ClientKeyID)
	}
	gotKID, err := clientVerificationMethodID(fx.ClientDID)
	if err != nil {
		t.Fatalf("clientVerificationMethodID: %v", err)
	}
	if gotKID != fx.ClientKeyID {
		t.Errorf("resolved verification method id = %q, want %q", gotKID, fx.ClientKeyID)
	}

	// Our construction: byte-identical protected header segment and a
	// round trip through the same key.
	ourJWE, err := sealRequestJWE(fx.ExpectedRequestJWT, key)
	if err != nil {
		t.Fatalf("sealing request JWE: %v", err)
	}
	if got, want := strings.Split(ourJWE, ".")[0], strings.Split(fx.RequestJWE, ".")[0]; got != want {
		t.Errorf("our protected header segment = %q, want SDK segment %q", got, want)
	}
	if got := walletDecryptRequestJWE(t, ourJWE, key); got != fx.ExpectedRequestJWT {
		t.Error("our request JWE did not round-trip with the fixture key")
	}
}

type responseFixture struct {
	ProviderDID             string            `json:"providerDid"`
	ClientDID               string            `json:"clientDid"`
	ClientKeyID             string            `json:"clientKeyId"`
	ClientEdPrivateKeyJwk   jwk.JWK           `json:"clientEdPrivateKeyJwk"`
	DelegateDID             string            `json:"delegateDid"`
	ResponseSignerDID       string            `json:"responseSignerDid"`
	PIN                     string            `json:"pin"`
	SharedKeyB64U           string            `json:"sharedKey_b64u"`
	ProtectedHeaderJSON     string            `json:"protectedHeaderJson"`
	AADJSON                 string            `json:"aadJson"`
	ResponseJWE             string            `json:"responseJwe"`
	ExpectedResponseJWT     string            `json:"expectedResponseJwt"`
	ExpectedResponsePayload json.RawMessage   `json:"expectedResponsePayload"`
	RequestNonce            string            `json:"requestNonce"`
	RequestedScopes         []PermissionScope `json:"requestedScopes"`
}

// TestFixtureConnectResponse checks response interop against genuine SDK
// output: ECDH+HKDF shared-key derivation, the PIN-AAD splice, JWE
// decryption, JWT verification, payload equality, wrong-PIN rejection, and
// grant validation over the SDK-issued grants.
func TestFixtureConnectResponse(t *testing.T) {
	var fx responseFixture
	readFixture(t, "connect_response.json", &fx)

	clientX25519Priv := x25519PrivFromEdJWK(t, fx.ClientEdPrivateKeyJwk)

	// The wire protected header must match the bundled JSON byte-for-byte.
	headerRaw, err := base64.RawURLEncoding.DecodeString(strings.Split(fx.ResponseJWE, ".")[0])
	if err != nil {
		t.Fatalf("decoding JWE header: %v", err)
	}
	if string(headerRaw) != fx.ProtectedHeaderJSON {
		t.Errorf("wire protected header = %s, want %s", headerRaw, fx.ProtectedHeaderJSON)
	}

	// Independent ECDH+HKDF check: our derivation from the client key and
	// the header's epk must equal the bundled shared key.
	var header struct {
		EPK jwk.JWK `json:"epk"`
	}
	if err := json.Unmarshal(headerRaw, &header); err != nil {
		t.Fatalf("parsing JWE header: %v", err)
	}
	epkPub, err := base64.RawURLEncoding.DecodeString(header.EPK.X)
	if err != nil {
		t.Fatalf("decoding epk x: %v", err)
	}
	sharedKey, err := deriveResponseSharedKey(clientX25519Priv, ed25519.PublicKey(epkPub))
	if err != nil {
		t.Fatalf("deriving shared key: %v", err)
	}
	wantSharedKey, err := base64.RawURLEncoding.DecodeString(fx.SharedKeyB64U)
	if err != nil {
		t.Fatalf("decoding sharedKey_b64u: %v", err)
	}
	if !bytes.Equal(sharedKey, wantSharedKey) {
		t.Errorf("derived shared key does not match sharedKey_b64u")
	}

	// The PIN-AAD splice must reproduce the SDK's AAD byte-for-byte.
	aad, err := spliceHeaderPIN(headerRaw, fx.PIN)
	if err != nil {
		t.Fatalf("spliceHeaderPIN: %v", err)
	}
	if string(aad) != fx.AADJSON {
		t.Errorf("spliced AAD = %s, want %s", aad, fx.AADJSON)
	}

	// Full decryption path.
	jwtBytes, err := decryptResponseJWE(fx.ResponseJWE, clientX25519Priv, fx.PIN)
	if err != nil {
		t.Fatalf("decrypting SDK response JWE: %v", err)
	}
	if string(jwtBytes) != fx.ExpectedResponseJWT {
		t.Errorf("decrypted JWT does not match expectedResponseJwt")
	}

	payload, err := verifyJWT(string(jwtBytes))
	if err != nil {
		t.Fatalf("verifying SDK response JWT: %v", err)
	}
	if !jsonEqual(t, payload, fx.ExpectedResponsePayload) {
		t.Errorf("verified payload differs from expectedResponsePayload")
	}

	var response EnboxConnectResponse
	if err := json.Unmarshal(payload, &response); err != nil {
		t.Fatalf("parsing response payload: %v", err)
	}
	if response.ProviderDID != fx.ProviderDID {
		t.Errorf("providerDid = %q, want %q", response.ProviderDID, fx.ProviderDID)
	}
	if response.Audience != fx.ClientDID {
		t.Errorf("aud = %q, want %q", response.Audience, fx.ClientDID)
	}
	if response.DelegateDID != fx.DelegateDID {
		t.Errorf("delegateDid = %q, want %q", response.DelegateDID, fx.DelegateDID)
	}
	if response.Nonce != fx.RequestNonce {
		t.Errorf("nonce = %q, want %q", response.Nonce, fx.RequestNonce)
	}
	if len(response.DelegateGrants) != 10 {
		t.Errorf("len(delegateGrants) = %d, want 10", len(response.DelegateGrants))
	}
	if len(response.SessionRevocations) != 5 {
		t.Errorf("len(sessionRevocations) = %d, want 5", len(response.SessionRevocations))
	}

	// Grant validation must accept the genuine SDK grants (5 session
	// grants + 5 revocation grants) against the requested scopes.
	requested := []ConnectPermissionRequest{{PermissionScopes: fx.RequestedScopes}}
	if err := validateGrants(response.DelegateGrants, fx.DelegateDID, requested, response.SessionRevocations); err != nil {
		t.Errorf("validateGrants rejected genuine SDK grants: %v", err)
	}

	// A wrong PIN must fail AAD authentication.
	if _, err := decryptResponseJWE(fx.ResponseJWE, clientX25519Priv, fx.PIN+"0"); err == nil {
		t.Error("expected decryption failure with a wrong PIN")
	}
}
