/**
 * Cross-language encryption interop validator.
 *
 * Reads test vectors from vectors.json (generated by Go) and validates every
 * primitive against the TypeScript DWN SDK implementation (@enbox/crypto).
 *
 * Usage: bun run testdata/interop/validate_vectors.ts
 *
 * Exit code 0 = all vectors match. Non-zero = mismatch found.
 */

import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

// Import DWN crypto primitives.
import { X25519, AesGcm, AesKw, ConcatKdf, Hkdf } from '@enbox/crypto';
import type { Jwk, ConcatKdfFixedInfo } from '@enbox/crypto';

// ---- Helpers ----

function b64ToBytes(s: string): Uint8Array {
  // Base64url without padding -> standard base64
  let base64 = s.replace(/-/g, '+').replace(/_/g, '/');
  // Add padding if needed
  while (base64.length % 4 !== 0) {
    base64 += '=';
  }
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

function bytesToB64(bytes: Uint8Array): string {
  let binary = '';
  for (const byte of bytes) {
    binary += String.fromCharCode(byte);
  }
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

function bytesEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) {
    if (a[i] !== b[i]) return false;
  }
  return true;
}

// ---- Vector types ----

interface Vectors {
  version: string;
  generatedBy: string;
  hkdf: HKDFVector[];
  concatKdf: ConcatKDFVector[];
  aead: AEADVector[];
  keyWrap: KeyWrapVector[];
  ecdhEs: ECDHESVector[];
  fullJwe: FullJWEVector[];
  protocolKey: ProtocolKeyVector[];
}

interface HKDFVector {
  description: string;
  rootKey: string;
  path: string[];
  derivedKey: string;
  publicKey: string;
}

interface ConcatKDFVector {
  description: string;
  sharedSecret: string;
  keyDataLen: number;
  algorithmId: string;
  partyUInfo: string;
  partyVInfo: string;
  suppPubInfo: number;
  derivedKey: string;
}

interface AEADVector {
  description: string;
  algorithm: string;
  key: string;
  iv: string;
  plaintext: string;
  ciphertext: string;
  tag: string;
}

interface KeyWrapVector {
  description: string;
  kek: string;
  plaintext: string;
  wrapped: string;
}

interface ECDHESVector {
  description: string;
  recipientPrivateKey: string;
  recipientPublicKey: string;
  ephemeralPrivateKey: string;
  ephemeralPublicKey: string;
  cek: string;
  sharedSecret: string;
  kek: string;
  wrappedKey: string;
}

interface FullJWEVector {
  description: string;
  recipientPrivateKey: string;
  recipientPublicKey: string;
  recipientKid: string;
  derivationScheme: string;
  plaintext: string;
  cek: string;
  iv: string;
  ciphertext: string;
  jwe: {
    protected: string;
    iv: string;
    tag: string;
    recipients: Array<{
      header: {
        kid: string;
        epk: { kty: string; crv: string; x: string };
        derivationScheme: string;
      };
      encrypted_key: string;
    }>;
  };
}

interface ProtocolKeyVector {
  description: string;
  rootKey: string;
  rootKeyId: string;
  protocolUri: string;
  protocolPath: string;
  fullPath: string[];
  derivedKey: string;
  publicKey: string;
}

// ---- Test runner ----

let passed = 0;
let failed = 0;

function pass(section: string, name: string): void {
  passed++;
  console.log(`  ✓ ${section}: ${name}`);
}

function fail(section: string, name: string, detail: string): void {
  failed++;
  console.error(`  ✗ ${section}: ${name}`);
  console.error(`    ${detail}`);
}

// ---- HKDF validation ----

async function validateHKDF(vectors: HKDFVector[]): Promise<void> {
  console.log('\n=== HKDF Key Derivation ===');

  for (const v of vectors) {
    try {
      const rootKey = b64ToBytes(v.rootKey);

      // Iteratively derive through each path segment using HKDF-SHA256
      // (matching dwn-sdk-js HdKey.derivePrivateKeyBytes).
      let currentKey = rootKey;
      for (const segment of v.path) {
        currentKey = await Hkdf.deriveKeyBytes({
          baseKeyBytes: currentKey,
          hash:         'SHA-256',
          salt:         new Uint8Array(0),
          info:         new TextEncoder().encode(segment),
          length:       256,
        });
      }

      const expectedDerived = b64ToBytes(v.derivedKey);
      if (!bytesEqual(currentKey, expectedDerived)) {
        fail('HKDF', v.description,
          `derived key mismatch: got ${bytesToB64(currentKey)}, want ${v.derivedKey}`);
        continue;
      }

      // Verify X25519 public key derivation.
      const privJwk = await X25519.bytesToPrivateKey({ privateKeyBytes: currentKey });
      const pubJwk = await X25519.getPublicKey({ key: privJwk });
      const pubBytes = await X25519.publicKeyToBytes({ publicKey: pubJwk });
      const expectedPub = b64ToBytes(v.publicKey);

      if (!bytesEqual(pubBytes, expectedPub)) {
        fail('HKDF', v.description,
          `public key mismatch: got ${bytesToB64(pubBytes)}, want ${v.publicKey}`);
        continue;
      }

      pass('HKDF', v.description);
    } catch (err) {
      fail('HKDF', v.description, `error: ${err}`);
    }
  }
}

// ---- Concat KDF validation ----

async function validateConcatKDF(vectors: ConcatKDFVector[]): Promise<void> {
  console.log('\n=== Concat KDF ===');

  for (const v of vectors) {
    try {
      const sharedSecret = b64ToBytes(v.sharedSecret);

      const derived = await ConcatKdf.deriveKey({
        sharedSecret,
        keyDataLen: v.keyDataLen,
        fixedInfo: {
          algorithmId: v.algorithmId,
          partyUInfo:  v.partyUInfo,
          partyVInfo:  v.partyVInfo,
          suppPubInfo: v.suppPubInfo,
        },
      });

      const expected = b64ToBytes(v.derivedKey);
      if (!bytesEqual(derived, expected)) {
        fail('ConcatKDF', v.description,
          `derived key mismatch: got ${bytesToB64(derived)}, want ${v.derivedKey}`);
        continue;
      }

      pass('ConcatKDF', v.description);
    } catch (err) {
      fail('ConcatKDF', v.description, `error: ${err}`);
    }
  }
}

// ---- AEAD validation ----

async function validateAEAD(vectors: AEADVector[]): Promise<void> {
  console.log('\n=== AEAD (A256GCM) ===');

  for (const v of vectors) {
    // Test encryption.
    try {
      const keyBytes = b64ToBytes(v.key);
      const iv = b64ToBytes(v.iv);
      const plaintext = b64ToBytes(v.plaintext);
      const expectedCT = b64ToBytes(v.ciphertext);
      const expectedTag = b64ToBytes(v.tag);

      const keyJwk = await AesGcm.bytesToPrivateKey({ privateKeyBytes: keyBytes });

      // Encrypt — Web Crypto returns ciphertext || tag.
      const sealed = await AesGcm.encrypt({ key: keyJwk, data: plaintext, iv });

      // Split ciphertext and tag (tag is last 16 bytes).
      const ct = sealed.slice(0, sealed.length - 16);
      const tag = sealed.slice(sealed.length - 16);

      if (!bytesEqual(ct, expectedCT)) {
        fail('AEAD encrypt', v.description,
          `ciphertext mismatch: got ${bytesToB64(ct)}, want ${v.ciphertext}`);
        continue;
      }
      if (!bytesEqual(tag, expectedTag)) {
        fail('AEAD encrypt', v.description,
          `tag mismatch: got ${bytesToB64(tag)}, want ${v.tag}`);
        continue;
      }

      pass('AEAD encrypt', v.description);
    } catch (err) {
      fail('AEAD encrypt', v.description, `error: ${err}`);
    }

    // Test decryption.
    try {
      const keyBytes = b64ToBytes(v.key);
      const iv = b64ToBytes(v.iv);
      const ct = b64ToBytes(v.ciphertext);
      const tag = b64ToBytes(v.tag);
      const expectedPlaintext = b64ToBytes(v.plaintext);

      const keyJwk = await AesGcm.bytesToPrivateKey({ privateKeyBytes: keyBytes });

      // Reassemble ciphertext || tag.
      const sealed = new Uint8Array(ct.length + tag.length);
      sealed.set(ct, 0);
      sealed.set(tag, ct.length);

      const plaintext = await AesGcm.decrypt({ key: keyJwk, data: sealed, iv });

      if (!bytesEqual(plaintext, expectedPlaintext)) {
        fail('AEAD decrypt', v.description,
          `plaintext mismatch: got ${bytesToB64(plaintext)}, want ${v.plaintext}`);
        continue;
      }

      pass('AEAD decrypt', v.description);
    } catch (err) {
      fail('AEAD decrypt', v.description, `error: ${err}`);
    }
  }
}

// ---- AES Key Wrap validation ----

async function validateKeyWrap(vectors: KeyWrapVector[]): Promise<void> {
  console.log('\n=== AES Key Wrap (RFC 3394) ===');

  for (const v of vectors) {
    // Test wrap.
    try {
      const kekBytes = b64ToBytes(v.kek);
      const cekBytes = b64ToBytes(v.plaintext);
      const expectedWrapped = b64ToBytes(v.wrapped);

      const kekJwk = await AesKw.bytesToPrivateKey({ privateKeyBytes: kekBytes });
      const cekJwk: Jwk = {
        kty: 'oct',
        k:   v.plaintext, // already base64url
        alg: 'A256GCM',
      };

      const wrapped = await AesKw.wrapKey({
        unwrappedKey:  cekJwk,
        encryptionKey: kekJwk,
      });

      if (!bytesEqual(wrapped, expectedWrapped)) {
        fail('KeyWrap wrap', v.description,
          `wrapped key mismatch: got ${bytesToB64(wrapped)}, want ${v.wrapped}`);
        continue;
      }

      pass('KeyWrap wrap', v.description);
    } catch (err) {
      fail('KeyWrap wrap', v.description, `error: ${err}`);
    }

    // Test unwrap.
    try {
      const kekBytes = b64ToBytes(v.kek);
      const wrappedBytes = b64ToBytes(v.wrapped);
      const expectedCEK = b64ToBytes(v.plaintext);

      const kekJwk = await AesKw.bytesToPrivateKey({ privateKeyBytes: kekBytes });

      const unwrappedJwk = await AesKw.unwrapKey({
        wrappedKeyBytes:     wrappedBytes,
        wrappedKeyAlgorithm: 'A256GCM',
        decryptionKey:       kekJwk,
      });

      const unwrappedBytes = await AesGcm.privateKeyToBytes({ privateKey: unwrappedJwk });

      if (!bytesEqual(unwrappedBytes, expectedCEK)) {
        fail('KeyWrap unwrap', v.description,
          `unwrapped CEK mismatch: got ${bytesToB64(unwrappedBytes)}, want ${v.plaintext}`);
        continue;
      }

      pass('KeyWrap unwrap', v.description);
    } catch (err) {
      fail('KeyWrap unwrap', v.description, `error: ${err}`);
    }
  }
}

// ---- ECDH-ES+A256KW validation ----

async function validateECDHES(vectors: ECDHESVector[]): Promise<void> {
  console.log('\n=== ECDH-ES+A256KW ===');

  for (const v of vectors) {
    try {
      const recipientPrivBytes = b64ToBytes(v.recipientPrivateKey);
      const recipientPubBytes = b64ToBytes(v.recipientPublicKey);
      const ephPrivBytes = b64ToBytes(v.ephemeralPrivateKey);
      const ephPubBytes = b64ToBytes(v.ephemeralPublicKey);
      const cekBytes = b64ToBytes(v.cek);
      const expectedShared = b64ToBytes(v.sharedSecret);
      const expectedKEK = b64ToBytes(v.kek);
      const expectedWrapped = b64ToBytes(v.wrappedKey);

      // Verify public key derivation.
      const recipientPrivJwk = await X25519.bytesToPrivateKey({ privateKeyBytes: recipientPrivBytes });
      const recipientPubJwk = await X25519.getPublicKey({ key: recipientPrivJwk });
      const gotRecipientPub = await X25519.publicKeyToBytes({ publicKey: recipientPubJwk });
      if (!bytesEqual(gotRecipientPub, recipientPubBytes)) {
        fail('ECDH-ES', v.description, 'recipient public key derivation mismatch');
        continue;
      }

      const ephPrivJwk = await X25519.bytesToPrivateKey({ privateKeyBytes: ephPrivBytes });
      const ephPubJwk = await X25519.getPublicKey({ key: ephPrivJwk });
      const gotEphPub = await X25519.publicKeyToBytes({ publicKey: ephPubJwk });
      if (!bytesEqual(gotEphPub, ephPubBytes)) {
        fail('ECDH-ES', v.description, 'ephemeral public key derivation mismatch');
        continue;
      }

      // Step 1: ECDH shared secret (ephemeral side).
      const recipientPubForDH = await X25519.bytesToPublicKey({ publicKeyBytes: recipientPubBytes });
      const sharedSecret = await X25519.sharedSecret({
        privateKeyA: ephPrivJwk,
        publicKeyB:  recipientPubForDH,
      });
      if (!bytesEqual(sharedSecret, expectedShared)) {
        fail('ECDH-ES', v.description,
          `shared secret mismatch: got ${bytesToB64(sharedSecret)}, want ${v.sharedSecret}`);
        continue;
      }

      // Verify ECDH symmetry (recipient side).
      const ephPubForDH = await X25519.bytesToPublicKey({ publicKeyBytes: ephPubBytes });
      const sharedSecretR = await X25519.sharedSecret({
        privateKeyA: recipientPrivJwk,
        publicKeyB:  ephPubForDH,
      });
      if (!bytesEqual(sharedSecret, sharedSecretR)) {
        fail('ECDH-ES', v.description, 'ECDH shared secret not symmetric');
        continue;
      }

      // Step 2: Concat KDF.
      const kek = await ConcatKdf.deriveKey({
        sharedSecret,
        keyDataLen: 256,
        fixedInfo: {
          algorithmId: 'A256KW',
          partyUInfo:  '',
          partyVInfo:  '',
          suppPubInfo: 256,
        },
      });
      if (!bytesEqual(kek, expectedKEK)) {
        fail('ECDH-ES', v.description,
          `KEK mismatch: got ${bytesToB64(kek)}, want ${v.kek}`);
        continue;
      }

      // Step 3: AES Key Wrap.
      const kekJwk = await AesKw.bytesToPrivateKey({ privateKeyBytes: kek });
      const cekJwk: Jwk = { kty: 'oct', k: v.cek, alg: 'A256GCM' };

      const wrapped = await AesKw.wrapKey({
        unwrappedKey:  cekJwk,
        encryptionKey: kekJwk,
      });
      if (!bytesEqual(wrapped, expectedWrapped)) {
        fail('ECDH-ES', v.description,
          `wrapped key mismatch: got ${bytesToB64(wrapped)}, want ${v.wrappedKey}`);
        continue;
      }

      // Verify unwrap.
      const unwrappedJwk = await AesKw.unwrapKey({
        wrappedKeyBytes:     wrapped,
        wrappedKeyAlgorithm: 'A256GCM',
        decryptionKey:       kekJwk,
      });
      const unwrappedBytes = await AesGcm.privateKeyToBytes({ privateKey: unwrappedJwk });
      if (!bytesEqual(unwrappedBytes, cekBytes)) {
        fail('ECDH-ES', v.description, 'unwrapped CEK does not match original');
        continue;
      }

      pass('ECDH-ES', v.description);
    } catch (err) {
      fail('ECDH-ES', v.description, `error: ${err}`);
    }
  }
}

// ---- Full JWE validation ----

async function validateFullJWE(vectors: FullJWEVector[]): Promise<void> {
  console.log('\n=== Full JWE Decrypt ===');

  for (const v of vectors) {
    try {
      const recipientPrivBytes = b64ToBytes(v.recipientPrivateKey);
      const ctBytes = b64ToBytes(v.ciphertext);
      const expectedPlaintext = b64ToBytes(v.plaintext);

      const jwe = v.jwe;

      // Find recipient by KID.
      const recipient = jwe.recipients.find(r => r.header.kid === v.recipientKid);
      if (!recipient) {
        fail('FullJWE', v.description, `no recipient found for KID ${v.recipientKid}`);
        continue;
      }

      // Decode ephemeral public key.
      const ephPubBytes = b64ToBytes(recipient.header.epk.x);

      // ECDH shared secret.
      const recipientPrivJwk = await X25519.bytesToPrivateKey({ privateKeyBytes: recipientPrivBytes });
      const ephPubJwk = await X25519.bytesToPublicKey({ publicKeyBytes: ephPubBytes });
      const sharedSecret = await X25519.sharedSecret({
        privateKeyA: recipientPrivJwk,
        publicKeyB:  ephPubJwk,
      });

      // Concat KDF.
      const kek = await ConcatKdf.deriveKey({
        sharedSecret,
        keyDataLen: 256,
        fixedInfo: {
          algorithmId: 'A256KW',
          partyUInfo:  '',
          partyVInfo:  '',
          suppPubInfo: 256,
        },
      });

      // Unwrap CEK.
      const wrappedKeyBytes = b64ToBytes(recipient.encrypted_key);
      const kekJwk = await AesKw.bytesToPrivateKey({ privateKeyBytes: kek });
      const cekJwk = await AesKw.unwrapKey({
        wrappedKeyBytes,
        wrappedKeyAlgorithm: 'A256GCM',
        decryptionKey:       kekJwk,
      });

      // Decode IV and tag from JWE.
      const iv = b64ToBytes(jwe.iv);
      const tag = b64ToBytes(jwe.tag);

      // Reassemble ciphertext || tag for AES-GCM.
      const sealed = new Uint8Array(ctBytes.length + tag.length);
      sealed.set(ctBytes, 0);
      sealed.set(tag, ctBytes.length);

      // Decrypt.
      const plaintext = await AesGcm.decrypt({ key: cekJwk, data: sealed, iv });

      if (!bytesEqual(plaintext, expectedPlaintext)) {
        fail('FullJWE', v.description,
          `plaintext mismatch: got ${new TextDecoder().decode(plaintext)}, want ${new TextDecoder().decode(expectedPlaintext)}`);
        continue;
      }

      pass('FullJWE', v.description);
    } catch (err) {
      fail('FullJWE', v.description, `error: ${err}`);
    }
  }
}

// ---- Protocol key derivation validation ----

async function validateProtocolKey(vectors: ProtocolKeyVector[]): Promise<void> {
  console.log('\n=== Protocol Key Derivation ===');

  for (const v of vectors) {
    try {
      const rootKey = b64ToBytes(v.rootKey);

      // Derive using the full path (matches Go's DerivePrivateKey).
      let currentKey = rootKey;
      for (const segment of v.fullPath) {
        currentKey = await Hkdf.deriveKeyBytes({
          baseKeyBytes: currentKey,
          hash:         'SHA-256',
          salt:         new Uint8Array(0),
          info:         new TextEncoder().encode(segment),
          length:       256,
        });
      }

      const expectedDerived = b64ToBytes(v.derivedKey);
      if (!bytesEqual(currentKey, expectedDerived)) {
        fail('ProtocolKey', v.description,
          `derived private key mismatch: got ${bytesToB64(currentKey)}, want ${v.derivedKey}`);
        continue;
      }

      // Verify public key.
      const privJwk = await X25519.bytesToPrivateKey({ privateKeyBytes: currentKey });
      const pubJwk = await X25519.getPublicKey({ key: privJwk });
      const pubBytes = await X25519.publicKeyToBytes({ publicKey: pubJwk });
      const expectedPub = b64ToBytes(v.publicKey);

      if (!bytesEqual(pubBytes, expectedPub)) {
        fail('ProtocolKey', v.description,
          `public key mismatch: got ${bytesToB64(pubBytes)}, want ${v.publicKey}`);
        continue;
      }

      pass('ProtocolKey', v.description);
    } catch (err) {
      fail('ProtocolKey', v.description, `error: ${err}`);
    }
  }
}

// ---- Main ----

async function main(): Promise<void> {
  console.log('DWN Encryption Cross-Language Interop Validation');
  console.log('================================================');

  // Load vectors.
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const vectorsPath = join(__dirname, 'vectors.json');
  const data = readFileSync(vectorsPath, 'utf-8');
  const vectors: Vectors = JSON.parse(data);

  console.log(`Vectors version: ${vectors.version}, generated by: ${vectors.generatedBy}`);

  await validateHKDF(vectors.hkdf);
  await validateConcatKDF(vectors.concatKdf);
  await validateAEAD(vectors.aead);
  await validateKeyWrap(vectors.keyWrap);
  await validateECDHES(vectors.ecdhEs);
  await validateFullJWE(vectors.fullJwe);
  await validateProtocolKey(vectors.protocolKey);

  console.log(`\n================================================`);
  console.log(`Results: ${passed} passed, ${failed} failed`);

  if (failed > 0) {
    process.exit(1);
  }
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
